In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import os
import sys
import random
import glob
import pickle
import itertools
import io
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score
import pandas
import time
from tqdm import tqdm

import sklearn

import tensorflow as tf

# utils lib for the tf dataset
import tf_data

In [4]:
data_path = {"ele_match": "/eos/user/r/rdfexp/ecal/cluster/output_deepcluster_dumper/windows_data/electrons/recordio_allinfo_v2/training/calo_matched/*.proto",
             "gamma_match": "/eos/user/r/rdfexp/ecal/cluster/output_deepcluster_dumper/windows_data/gammas/recordio_allinfo_v2/training/calo_matched/*.proto",
             "ele_nomatch": "/eos/user/r/rdfexp/ecal/cluster/output_deepcluster_dumper/windows_data/electrons/recordio_allinfo_v2/training/no_calo_matched/*.proto",
             "gamma_nomatch": "/eos/user/r/rdfexp/ecal/cluster/output_deepcluster_dumper/windows_data/gammas/recordio_allinfo_v2/training/no_calo_matched/*.proto"
            }

In [14]:
features = ["cluster_ieta","cluster_iphi","cluster_iz",
            "cluster_deta", "cluster_dphi",
            "en_cluster","et_cluster", 
            "cl_swissCross", "cl_nxtals", "cl_etaWidth","cl_phiWidth"]
features = ["et_cluster"]

In [6]:
_load_n_items = 10
_batch_size = 5
_nepochs = 100
_ntrain = 10000
_nval = 1000

In [15]:
dataset = tf.data.TFRecordDataset(tf.io.gfile.glob(data_path["ele_match"]))

dataset =  dataset.batch(_batch_size).map(
                lambda el: tf_data.parse_windows_batch(el, True),
                num_parallel_calls=tf.data.experimental.AUTOTUNE, deterministic=False)

dataset = tf_data.cluster_features_and_hits(dataset,features)

In [16]:
a = next(iter(dataset.take(1)))

In [17]:
cl_X, cl_hits, is_seed, in_sc,  cl_features = a

In [20]:
sum = 0.
N = 0. 
for ev in dataset:
    cl_X, cl_hits, is_seed, in_sc,  cl_features = ev
    tot_en = tf.reduce_sum(cl_X[:,:,0])
    print(tot_en)
    N = cl_X.shape[0] * cl_X.shape[1] 
    break
    

tf.Tensor(683.0, shape=(), dtype=float32)


In [ ]:
 for ev in dataset:
    #do your think
    break

In [24]:
a[1]['cl_h'][0]

<tf.Tensor: shape=(9, 4), dtype=float32, numpy=
array([[-41.        , 182.        ,   0.        ,  21.892532  ],
       [-41.        , 183.        ,   0.        ,   0.46643642],
       [-42.        , 183.        ,   0.        ,   0.2937847 ],
       [-42.        , 182.        ,   0.        ,   0.8742974 ],
       [-42.        , 181.        ,   0.        ,   0.56234646],
       [-41.        , 181.        ,   0.        ,   4.902018  ],
       [-40.        , 181.        ,   0.        ,   0.54801035],
       [-40.        , 182.        ,   0.        ,   0.7728225 ],
       [-39.        , 182.        ,   0.        ,   0.25400263]],
      dtype=float32)>

In [27]:
a[1]['cl_h'][3]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-37.        , 152.        ,   0.        ,   0.42435348]],
      dtype=float32)>